on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag mgcss-track-grupo2:latest

    - name: Publish Release
      uses: softprops/action-gh-release@273398327cb02c37346b0a8870191834925055b8
      with:
        files: target/*.jar
        # github.ref_name extrae solo el nombre (ej. v1.0.0) en vez de refs/tags/v1.0.0
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: ${{ github.event.head_commit.message }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}